package com.skyeye.dao;

import com.skyeye.model.FeedBack;

public interface FeedBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int insert(FeedBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbggenerated
     */
    int insertSelective(FeedBack record);
}