package com.skyeye.dao;

import com.skyeye.model.Groom;

public interface GroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groom
     *
     * @mbggenerated
     */
    int insert(Groom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groom
     *
     * @mbggenerated
     */
    int insertSelective(Groom record);
}