package com.skyeye.dao;

import com.skyeye.model.Seller;

public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbggenerated
     */
    int insertSelective(Seller record);
}