package com.skyeye.dao;

import com.skyeye.model.Setting;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table setting
     *
     * @mbggenerated
     */
    int insertSelective(Setting record);
}