package com.skyeye.model;

import java.util.Date;

public class FeedBack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.own_id
     *
     * @mbggenerated
     */
    private String ownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.belong_food_id
     *
     * @mbggenerated
     */
    private String belongFoodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.id
     *
     * @return the value of feedback.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.id
     *
     * @param id the value for feedback.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.own_id
     *
     * @return the value of feedback.own_id
     *
     * @mbggenerated
     */
    public String getOwnId() {
        return ownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.own_id
     *
     * @param ownId the value for feedback.own_id
     *
     * @mbggenerated
     */
    public void setOwnId(String ownId) {
        this.ownId = ownId == null ? null : ownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.belong_food_id
     *
     * @return the value of feedback.belong_food_id
     *
     * @mbggenerated
     */
    public String getBelongFoodId() {
        return belongFoodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.belong_food_id
     *
     * @param belongFoodId the value for feedback.belong_food_id
     *
     * @mbggenerated
     */
    public void setBelongFoodId(String belongFoodId) {
        this.belongFoodId = belongFoodId == null ? null : belongFoodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.create_time
     *
     * @return the value of feedback.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.create_time
     *
     * @param createTime the value for feedback.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}