package com.skyeye.model;

import java.util.Date;

public class Groom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groom.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groom.own_id
     *
     * @mbggenerated
     */
    private String ownId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groom.food_id
     *
     * @mbggenerated
     */
    private String foodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groom.belong_type
     *
     * @mbggenerated
     */
    private Integer belongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groom.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groom.id
     *
     * @return the value of groom.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groom.id
     *
     * @param id the value for groom.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groom.own_id
     *
     * @return the value of groom.own_id
     *
     * @mbggenerated
     */
    public String getOwnId() {
        return ownId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groom.own_id
     *
     * @param ownId the value for groom.own_id
     *
     * @mbggenerated
     */
    public void setOwnId(String ownId) {
        this.ownId = ownId == null ? null : ownId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groom.food_id
     *
     * @return the value of groom.food_id
     *
     * @mbggenerated
     */
    public String getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groom.food_id
     *
     * @param foodId the value for groom.food_id
     *
     * @mbggenerated
     */
    public void setFoodId(String foodId) {
        this.foodId = foodId == null ? null : foodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groom.belong_type
     *
     * @return the value of groom.belong_type
     *
     * @mbggenerated
     */
    public Integer getBelongType() {
        return belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groom.belong_type
     *
     * @param belongType the value for groom.belong_type
     *
     * @mbggenerated
     */
    public void setBelongType(Integer belongType) {
        this.belongType = belongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groom.create_time
     *
     * @return the value of groom.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groom.create_time
     *
     * @param createTime the value for groom.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}